micronaut:
  application:
    name: stock-monitor-practice
  test:
    resources:
      enabled: false

datasources:
  default:
    url: jdbc:mysql://localhost:3306/stockdb
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

jpa:
  default:
    entity-scan:
      packages:
        - com.stock.entities
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE